name: MelonStackedSpawners
version: 1.0
main: gg.blocky.melonstackedspawners.SpawnerPlugin
description: Plugin provided by Blocky Studios, LLC
authors: [ "Blocky Studios, LLC", "Cody Lynn" ]
depend: [ HolographicDisplays, SilkSpawners, StackMob ]
api-version: 1.17
website: https://blocky.gg/